### ISSUE TITLE
Error for Unban

### ISSUE THREAD

**Issue by TimeMultiverse** [kohls-admin/kohls-admin#124]
### Did you check for existing issues?

- [X] I have searched the open and **closed** bugs.

### Platform

PC

### Version

624f629

### Description

There are bunch of users that are deleted that requested the account deletion.

### Repro

- Run ;ban 5 -1 test
- Run ;unban 5
- Thrown an error
- The user is deleted but successful unbanned yet the error is thrown.

![image](https://github.com/user-attachments/assets/20031e7c-7383-43e8-9a70-f9e2592ed257)

**Comment by kohltastrophe** [comment]
Fixed in 7c54847
