### ISSUE TITLE
The settings tab is gone

### ISSUE THREAD

**Issue by TheHackerLxr** [kohls-admin/kohls-admin#130]
### Did you check for existing issues?

- [X] I have searched the open and **closed** bugs.

### Platform

PC

### Version

ee84edf

### Description

![image](https://github.com/user-attachments/assets/d1dbba4f-6b26-462e-a81b-fd6d35de68cf)
The settings tab is just gone, I literally can't find it. (maybe im blind)

### Details

No logs

**Comment by TheHackerLxr** [comment]
I found why it was missing, now the creator himself customizes the values for certain tabs in the settings, sorry for the mistake

**Comment by kohltastrophe** [comment]
Fixed in 5eb9c68
