### ISSUE TITLE
CUSTOM RANKSS

### ISSUE THREAD

**Issue by 7-7what** [kohls-admin/kohls-admin#143]
### Did you check for existing issues?

- [X] I have searched the open and **closed** feature requests.

### Description

I'd love to be able to make custom ranks, if so you can already.. then i'd like to know how to use it in ka new and ka legacy. 

if you cant, please add to ka new, and if  you wont do this, i anyways know you guys dont work on legacy no more, but please add custom ranks to legacy, or dont! but i'd love for it to be in the new one anyway.

**Comment by kohltastrophe** [comment]
In the Settings Modulescript of the new admin you can define as many roles as you want with different permissions, just copy one of the default roles and change the unique key.
