### ISSUE TITLE
Golden crown and wings (spinning and animated)

### ISSUE THREAD

**Issue by TheHackerLxr** [kohls-admin/kohls-admin#145]
### Did you check for existing issues?

- [X] I have searched the open and **closed** feature requests.

### Description

![image](https://github.com/user-attachments/assets/b9ea6743-bcd1-4116-8b5f-f9e3ab3f2e9d)
![image](https://github.com/user-attachments/assets/6530f71f-86e4-4d5a-8fec-6976ddb02e49)

They are in the catalog, but not in the admin panel. Please add gold versions too. 🙏

**Comment by kohltastrophe** [comment]
Added in 2de71f0
