### ISSUE TITLE
Gear command

### ISSUE THREAD

**Issue by TheHackerLxr** [kohls-admin/kohls-admin#44]
https://github.com/user-attachments/assets/72473ce3-51cb-4832-af03-3cb30775d898

I tried to give myself gear, but it didn't work because the item ID wasn't determined. Sorry for giving too much work, I'm just trying to notice more bugs. Thanks if you fix it! 🙏

**Comment by kohltastrophe** [comment]
The `give` command is for tools that are placed in the `ServerStorage` or `Lighting` by the Game Developer. I haven't added a gear command yet, that will come when the alpha is ready to replace KAI as the default because of Roblox security limitations with new marketplace assets.

**Comment by TheHackerLxr** [comment]
> The `give` command is for tools that are placed in the `ServerStorage` or `Lighting` by the Game Developer. I haven't added a gear command yet, that will come when the alpha is ready to replace KAI as the default because of Roblox security limitations with new marketplace assets.

Thanks for this information! 👍
