### ISSUE TITLE
Fix unjail command not working

### ISSUE THREAD

**Issue by TheHackerLxr** [kohls-admin/kohls-admin#63]
![Screenshot_20240920_001630_Roblox.jpg](https://github.com/user-attachments/assets/7af54520-5052-46cd-b5ef-df21e2eb5101)

For some reason unjail command was not working and just gave me errors! Thanks for fixing! ❤️

**Comment by kohltastrophe** [comment]
It gets the bounding box of your character for the jail, this will make it work on characters with a large size. It's big because of your wings.
