### ISSUE TITLE
Commands with effects a little broken on r6

### ISSUE THREAD

**Issue by TheHackerLxr** [kohls-admin/kohls-admin#66]
### Have you searched for existing issues? 🔍

- [X] I have searched the existing open and closed issues.

### Kohl's Admin Version 🔢

2aa753d

### What Happened? 🤔

https://github.com/user-attachments/assets/0b7bd3c8-3802-46b2-91fd-a10590d8b93b

https://github.com/user-attachments/assets/018b0f6c-a55c-4708-82a8-d01d97279caf

https://github.com/user-attachments/assets/c7388f18-a3b2-48e2-be96-df0498cf01f1

https://github.com/user-attachments/assets/be101125-2215-4860-b8a5-4d7d3e4fe028

effects like fire, smoke, sparkles and others should be attached to the body on r6, not the head

### Steps to Reproduce 🪜

make your body R6, try :smoke me, :sparkles me, :fire me and other commands that gives effects.

**Comment by kohltastrophe** [comment]
This seems to be an issue with using Character.PrimaryPart instead of directly searching for a humanoid root part or torso part to place the effect inside of.
